In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Aggregate climate and soil data 2021-25 (0-15cm depth).csv')
df.shape

(1920, 13)

In [ ]:
df.head()

,district,Year,Month,Season,rainfall,temperature,humidity,ph,organic_carbon,sand,clay,silt,soil_texture
0,Bharatpur,2021.0,1.0,Rabi,15.981440,14.500948,70.282786,7.735500,0.872053,44.874517,27.175172,27.950114,Clay Loam
1,Dhaulpur,2021.0,1.0,Rabi,11.219040,15.018434,69.689840,7.655289,0.830296,43.900628,26.544170,29.555066,Loam
2,Kota,2021.0,1.0,Rabi,6.413589,17.202463,62.059693,7.331463,0.822336,40.751248,28.378044,30.870638,Clay Loam
3,Baran,2021.0,1.0,Rabi,7.956854,17.594477,58.118694,7.310499,0.787739,41.227558,27.577051,31.195185,Clay Loam
4,Jaipur,2021.0,1.0,Rabi,8.837742,14.291422,63.971722,7.468534,0.850232,47.746106,23.499579,28.754366,Loam

In [ ]:
df.columns

Index(['district', 'Year', 'Month', 'Season', 'rainfall', 'temperature',
       'humidity', 'ph', 'organic_carbon', 'sand', 'clay', 'silt',
       'soil_texture'],
      dtype='object')

In [ ]:
def expand_with_crops(df, crop_mapping):
    rows = []

    for _, row in df.iterrows():
        district = row['district']
        season = row['Season']

        # Get crops for that district + season
        crops = crop_mapping.get(district, {}).get(season, [])

        for crop in crops:
            new_row = row.copy()
            new_row['target_crop'] = crop
            rows.append(new_row)

    return pd.DataFrame(rows)

In [ ]:
# crop_mappings = {
#     'Kota': {
#         'Rabi': ['Coriander', 'Garlic', 'Mustard', 'Fenugreek', 'Kalonji'],
#         'Kharif': ['Soybean']
#     },
#     'Udaipur': {
#         'Rabi': ['Ajwain', 'Isabgol', 'Kalonji', 'Garlic'],
#         'Kharif': ['Ginger', 'Custard Apple', 'Safed Musli', 'Ashwagandha']
#     },
#     'Jaisalmer': {
#         'Rabi': ['Cumin', 'Isabgol', 'Mustard'],
#         'Kharif': ['Guar', 'Moth Bean', 'Groundnut', 'Castor']
#     },
#     'Ajmer': {
#         'Rabi': ['Coriander', 'Fennel', 'Fenugreek', 'Ajwain', 'Nigella', 'Chilli'],
#         'Kharif': ['Onion', 'Cauliflower', 'Chilli', 'Okra']
#     },
#     'Jodhpur': {
#         'Rabi': ['Cumin', 'Isabgol', 'Onion', 'Garlic', 'Red Chilli', 'Mustard'],
#         'Kharif': ['Onion', 'Castor']
#     },
#     'Jaipur': {
#         'Rabi': ['Mustard', 'Fenugreek', 'Garden Pea', 'Onion', 'Chilli', 'Barley'],
#         'Kharif': ['Groundnut', 'Chilli', 'Sesamum']
#     },
#     'Alwar': {
#         'Rabi': ['Mustard', 'Onion', 'Barley ',  'Garlic', 'Green Pea', 'Fodder Beet'],
#         'Kharif': ['Onion', 'Cotton', 'Tomato']
#     },
#     'Banswara': {
#         'Rabi': ['Ajwain', 'Tomato', 'Onion', 'Chilli'],
#         'Kharif': ['Ginger', 'Safed Musli', 'Soybean', 'Custard Apple', 'Pigeon Pea']
#     },
#     'Baran': {
#         'Rabi': ['Garlic', 'Coriander', 'Mustard', 'Chickpea'],
#         'Kharif': ['Soybean', 'Urdbean', 'Ashwagandha']
#     },
#     'Barmer': {
#         'Rabi': ['Cumin', 'Isabgol', 'Mustard'],
#         'Kharif': ['Castor', 'Cluster Bean', 'Sesame', 'Groundnut']
#     },
#     'Bharatpur': {
#         'Rabi': ['Indian Mustard', 'Wheat', 'Chickpea ', 'Potato', 'Fennel'],
#         'Kharif': ['Onion', 'Tomato']
#     },
#     'Bhilwara': {
#         'Rabi': ['Mustard', 'Garlic', 'Coriander', 'Ashwagandha'],
#         'Kharif': ['Groundnut', 'Sesame']
#     },
#     'Bikaner': {
#         'Rabi': ['Mustard', 'Cumin', 'Isabgol'],
#         'Kharif': ['Groundnut', 'Cluster Bean', 'Moth Bean']
#     },
#     'Bundi': {
#         'Rabi': ['Mustard', 'Potato', 'Cheakpea'],
#         'Kharif': ['Soybean', 'Okra', 'Maize']
#     },
#     'Chittorgarh': {
#         'Rabi': ['Ajwain','Garlic', 'Fenugreek'],
#         'Kharif': ['Soybean', 'Groundnut', 'Ashwagandha']
#     },
#     'Churu': {
#         'Rabi': ['Cumin', 'Isabgol', 'Fenugreek'],
#         'Kharif': ['Gaur', 'Moth Bean']
#     },
#     'Dausa': {
#         'Rabi': ['Wheat', 'Musturd', 'Chickpea'],
#         'Kharif': ['Bajra', 'Groundnut', 'Tomato']
#     },
#     'Dholpur': {
#         'Rabi': ['Musturd', 'Potato', ''],
#         'Kharif': ['Bajra', 'Sesame', 'Guar']
#     },
#     'Dungarpur': {
#         'Rabi': ['Onion', 'Chilli', 'Cheakpea'],
#         'Kharif': ['Ginger', 'Turmeric', 'Blackgram']
#     },

#     'Hanumangarh': {
#         'Rabi': ['Mustard', 'Wheat', 'Gram', 'Barley'],
#         'Kharif': ['Cotton', 'Guar', 'Rice', 'Groundnut', 'Mungbean', 'Castor']
#     },
#     'Jalore': {
#         'Rabi': ['Isabgol', 'Mustard', 'Fennel', 'Tomato'],
#         'Kharif': ['Castor', 'Chilli', 'Sesame']
#     },
#     'Jhalawar': {
#         'Rabi': ['Garlic', 'Coriander', 'Mustard', 'Ashwagandha',  'Fodder Beet', 'Strawberry'],
#         'Kharif': ['Soybean']
#     },
#     'Jhunjhunu': {
#         'Rabi': ['Mustard', 'Isabgol', 'Fenugreek', 'Chickpea', 'Fodder Beet'],
#         'Kharif': ['Guar', 'Moong Bean', 'Groundnut']
#     },
#     'Karauli': {
#         'Rabi': ['Mustard', 'Tomato', 'Chickpea', 'Brinjal'],
#         'Kharif': ['Sesame', 'Chilli' 'Guar']
#     },
#     'Nagaur': {
#         'Rabi': ['Cumin', 'Isabgol', 'Mustard', 'Onion', 'Fenugreek'],
#         'Kharif': ['Groundnut', 'Moong Bean', 'Moth Bean', 'Onion']
#     },
#     'Pali': {
#         'Rabi': ['Cumin', 'Fennel', 'Mustard '],
#         'Kharif': ['Mehandi', 'Sesame', 'Castor']
#     },
#     'Rajsamand': {
#         'Rabi': ['Pomegranate', 'Garlic', 'Tomato', 'Onion'],
#         'Kharif': ['Custard Apple', 'Groundnut', 'Sesame']
#     },
#     'Sawai Madhopur': {
#         'Rabi': ['Mustard', 'Garlic', 'Fenugreek', 'Chilli', 'Tomato'],
#         'Kharif': ['Guava', 'Sesame', 'Soybean', 'Groundnut']
#     },
#     'Sikar': {
#         'Rabi': ['Mustard', 'Fenugreek', 'Onion', 'Garlic', 'Taramira'],
#         'Kharif': ['Groundnut', 'Green Gram', 'Onion', 'Cluster Bean', 'Cowpea']
#     },
#     'Sirohi': {
#         'Rabi': ['Castor', 'Fennel', 'Cumin', 'Isabgol', 'Tomato', 'Mustard'],
#         'Kharif': ['Castor', 'Groundnut', 'Tomato']
#     },
#     'Sri Ganganagar': {
#         'Rabi': ['Mustard', 'Chickpea', 'Onion', 'Coriander', 'Fenugreek', 'Taramira'],
#         'Kharif': ['American Cotton', 'Guar', 'Onion', 'Mungbean']
#     },
#     'Tonk': {
#         'Rabi': ['Mustard', 'Fennel', 'Onion'],
#         'Kharif': ['Groundnut', 'Chilli', 'Green Gram']
#     }
# }

In [ ]:
final_crop_mappings = {
    'Kota': {
        'Rabi': ['Coriander', 'Garlic', 'Mustard', 'Fenugreek', 'Kalonji'],
        'Kharif': ['Soybean']
    },
    'Udaipur': {
        'Rabi': ['Ajwain', 'Isabgol', 'Kalonji', 'Garlic'],
        'Kharif': ['Ginger', 'Custard Apple', 'Safed Musli', 'Ashwagandha']
    },
    'Jaisalmer': {
        'Rabi': ['Cumin', 'Isabgol', 'Mustard'],
        'Kharif': ['Guar', 'Moth Bean', 'Groundnut', 'Castor']
    },
    'Ajmer': {
        'Rabi': [ 'Coriander', 'Fennel', 'Fenugreek', 'Ajwain', 'Kalonji', 'Chilli'],
        'Kharif': ['Onion', 'Cauliflower', 'Chilli', 'Okra']
    },
    'Jodhpur': {
        'Rabi': ['Cumin', 'Isabgol', 'Onion', 'Garlic', 'Chilli', 'Mustard'],
        'Kharif': ['Onion', 'Castor']
    },
    'Jaipur': {
        'Rabi': ['Mustard', 'Fenugreek', 'Pea', 'Onion', 'Chilli', 'Barley'],
        'Kharif': ['Groundnut', 'Chilli', 'Sesame']
    },
    'Alwar': {
        'Rabi': ['Mustard', 'Onion', 'Barley', 'Garlic', 'Pea'],
        'Kharif': ['Onion', 'Cotton', 'Tomato']
    },
    'Banswara': {
        'Rabi': ['Ajwain', 'Tomato', 'Onion', 'Chilli'],
        'Kharif': ['Ginger', 'Safed Musli', 'Soybean', 'Custard Apple', 'Pigeon Pea']
    },
    'Baran': {
        'Rabi': ['Garlic', 'Coriander', 'Mustard', 'Chickpea'],
        'Kharif': ['Soybean', 'Blackgram', 'Ashwagandha']
    },
    'Barmer': {
        'Rabi': ['Cumin', 'Isabgol', 'Mustard'],
        'Kharif': ['Castor', 'Guar', 'Sesame', 'Groundnut']
    },
    'Bharatpur': {
        'Rabi': ['Mustard', 'Wheat', 'Chickpea', 'Potato', 'Fennel'],
        'Kharif': ['Onion', 'Tomato']
    },
    'Bhilwara': {
        'Rabi': ['Mustard', 'Garlic', 'Coriander', 'Ashwagandha'],
        'Kharif': ['Groundnut', 'Sesame']
    },
    'Bikaner': {
        'Rabi': ['Mustard', 'Cumin', 'Isabgol'],
        'Kharif': ['Groundnut', 'Guar', 'Moth Bean']
    },
    'Bundi': {
        'Rabi': ['Mustard', 'Potato', 'Chickpea'],
        'Kharif': ['Soybean', 'Okra', 'Maize']
    },
    'Chittorgarh': {
        'Rabi': ['Ajwain', 'Garlic', 'Fenugreek'],
        'Kharif': ['Soybean', 'Groundnut', 'Ashwagandha']
    },
    'Churu': {
        'Rabi': ['Cumin', 'Isabgol', 'Fenugreek'],
        'Kharif': ['Guar', 'Moth Bean']
    },
    'Dausa': {
        'Rabi': ['Wheat', 'Mustard', 'Chickpea'],
        'Kharif': ['Bajra', 'Groundnut', 'Tomato']
    },
    'Dholpur': {
        'Rabi': ['Mustard', 'Potato'],
        'Kharif': ['Bajra', 'Sesame', 'Guar']
    },
    'Dungarpur': {
        'Rabi': ['Onion', 'Chilli', 'Chickpea'],
        'Kharif': ['Ginger', 'Turmeric', 'Blackgram']
    },
    'Hanumangarh': {
        'Rabi': ['Mustard', 'Wheat', 'Chickpea', 'Barley'],
        'Kharif': ['Cotton', 'Guar', 'Rice', 'Groundnut', 'Mungbean', 'Castor']
    },
    'Jalore': {
        'Rabi': ['Isabgol', 'Mustard', 'Fennel', 'Tomato'],
        'Kharif': ['Castor', 'Chilli', 'Sesame']
    },
    'Jhalawar': {
        'Rabi': ['Garlic', 'Coriander', 'Mustard', 'Ashwagandha'],
        'Kharif': ['Soybean']
    },
    'Jhunjhunu': {
        'Rabi': ['Mustard', 'Isabgol', 'Fenugreek', 'Chickpea'],
        'Kharif': ['Guar', 'Mungbean', 'Groundnut']
    },
    'Karauli': {
        'Rabi': ['Mustard', 'Tomato', 'Chickpea', 'Brinjal'],
        'Kharif': ['Sesame', 'Chilli', 'Guar']
    },
    'Nagaur': {
        'Rabi': ['Cumin', 'Isabgol', 'Mustard', 'Onion', 'Fenugreek'],
        'Kharif': ['Groundnut', 'Mungbean', 'Moth Bean', 'Onion']
    },
    'Pali': {
        'Rabi': ['Cumin', 'Fennel', 'Mustard'],
        'Kharif': ['Mehandi', 'Sesame', 'Castor']
    },
    'Rajsamand': {
        'Rabi': ['Pomegranate', 'Garlic', 'Tomato', 'Onion'],
        'Kharif': ['Custard Apple', 'Groundnut', 'Sesame']
    },
    'Sawai Madhopur': {
        'Rabi': ['Mustard', 'Garlic', 'Fenugreek', 'Chilli', 'Tomato'],
        'Kharif': ['Guava', 'Sesame', 'Soybean', 'Groundnut']
    },
    'Sikar': {
        'Rabi': ['Mustard', 'Fenugreek', 'Onion', 'Garlic', 'Taramira'],
        'Kharif': ['Groundnut', 'Mungbean', 'Onion', 'Guar', 'Cowpea']
    },
    'Sirohi': {
        'Rabi': ['Castor', 'Fennel', 'Cumin', 'Isabgol', 'Tomato', 'Mustard'],
        'Kharif': ['Castor', 'Groundnut', 'Tomato']
    },
    'Sri Ganganagar': {
        'Rabi': ['Mustard', 'Chickpea', 'Onion', 'Coriander', 'Fenugreek', 'Taramira'],
        'Kharif': ['Cotton', 'Guar', 'Onion', 'Mungbean']
    },
    'Tonk': {
        'Rabi': ['Mustard', 'Fennel', 'Onion'],
        'Kharif': ['Groundnut', 'Chilli', 'Mungbean']
    }
}

In [ ]:
df_final = expand_with_crops(df, final_crop_mappings)

In [ ]:
df_final.shape

(4975, 14)

In [ ]:
df_final.head()

,district,Year,Month,Season,rainfall,temperature,humidity,ph,organic_carbon,sand,clay,silt,soil_texture,target_crop
0,Bharatpur,2021.0,1.0,Rabi,15.98144,14.500948,70.282786,7.7355,0.872053,44.874517,27.175172,27.950114,Clay Loam,Mustard
0,Bharatpur,2021.0,1.0,Rabi,15.98144,14.500948,70.282786,7.7355,0.872053,44.874517,27.175172,27.950114,Clay Loam,Wheat
0,Bharatpur,2021.0,1.0,Rabi,15.98144,14.500948,70.282786,7.7355,0.872053,44.874517,27.175172,27.950114,Clay Loam,Chickpea
0,Bharatpur,2021.0,1.0,Rabi,15.98144,14.500948,70.282786,7.7355,0.872053,44.874517,27.175172,27.950114,Clay Loam,Potato
0,Bharatpur,2021.0,1.0,Rabi,15.98144,14.500948,70.282786,7.7355,0.872053,44.874517,27.175172,27.950114,Clay Loam,Fennel

In [ ]:
df_final.to_csv('Crop mapped with climate and soil data 2021-25 (0-15cm depth).csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
output_path = '/content/drive/MyDrive/EarthEngine/Crop mapped with climate and soil data 2021-25 (0-15cm depth).csv'
df_final.to_csv(output_path, index=False)
print(f'DataFrame saved to {output_path}')

DataFrame saved to /content/drive/MyDrive/EarthEngine/Crop mapped with climate and soil data 2021-25 (0-15cm depth).csv

In [ ]:
df_final['target_crop'].value_counts()

target_crop
Mustard          525
Onion            375
Groundnut        325
Chilli           250
Garlic           250
Tomato           225
Cumin            200
Isabgol          200
Fenugreek        175
Castor           175
Chickpea         175
Sesame           175
Guar             175
Soybean          150
Coriander        125
Fennel           125
Ashwagandha      100
Mungbean         100
Moth Bean        100
Custard Apple     75
Ginger            75
Kalonji           75
Wheat             75
Barley            75
Ajwain            75
Pea               50
Potato            50
Cotton            50
Safed Musli       50
Okra              50
Blackgram         50
Taramira          25
Brinjal           25
Pomegranate       25
Bajra             25
Rice              25
Guava             25
Cauliflower       25
Pigeon Pea        25
Maize             25
Turmeric          25
Mehandi           25
Cowpea            25
Name: count, dtype: int64